site_name: "dinarasaurae's webdev"
theme:
  name: 'material'
  palette:
    primary: 'orange'
    accent: 'red'

nav:
  - Home: index.md
  - LAB №1:
    - Base classes: lab1/base.md
    - Task 1: lab1/task1.md
    - Task 2: lab1/task2.md
    - Task 3: lab1/task3.md
    - Task 4: lab1/task4.md
    - Task 5: lab1/task5.md
  - LAB №2:
    - Data model: lab2/data.md
    - Registration: lab2/registration.md
    - Authorization: lab2/authorization.md
    - Dashboard: lab2/dashboard.md
    - Menu: lab2/menu.md
    - Search: lab2/search.md
    - Submission: lab2/submission.md
    - Homework: lab2/homeworks.md
  - LAB №3:
      - Practical work 3.1: lab3/practical_work_3_1.md
      - Practical work 3.2: lab3/practical_work_3_2.md
      - Practical work 3.3: lab3/practical_work_3_3.md 
      - Practical work DRF: lab3/practical_work_drf.md
      - Practical work DRF Generic: lab3/practical_work_drf_generic.md